name: movies_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  beamer: ^1.5.3
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^5.0.2
  flutter:
    sdk: flutter
  flutter_loggy_dio: ^3.0.1
  form_builder_validators: ^8.5.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.2
  json_annotation: ^4.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  retrofit_generator: null

flutter:
  uses-material-design: true

  assets:
    - assets/images/
